#!/bin/bash
#SBATCH --nodes=1                   # 1 node
#SBATCH --ntasks=4                  # total MPI tasks across nodes
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=8          # OpenMP threads per MPI task
#SBATCH --mem=0                     # use all available memory
#SBATCH --partition=EPYC
#SBATCH -t 00:05:00                 # 5 minutes for profiling and test runs
#SBATCH --job-name=testing

# Set OpenMP variables
export OMP_NUM_THREADS=8
export OMP_PLACES=cores
export OMP_PROC_BIND=close
export OMP_DISPLAY_AFFINITY=TRUE

# Load MPI module if needed
module load openMPI/5.0.5



echo "Running default, non-optimized version"
mpicc -o main -O2 -fopenmp -march=native  -Iinclude ../src/stencil_template_parallel.c
mpirun -np 4 --map-by core --bind-to core ./main  -n 1000 -e 30 -p 1 -o 0 > output.log
