#!/bin/bash
#SBATCH --nodes=1                   # 1 node
#SBATCH --ntasks=1                  # total MPI tasks across nodes
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8          # OpenMP threads per MPI task
#SBATCH --mem=0                     # use all available memory
#SBATCH --partition=EPYC
#SBATCH -t 00:00:20                 # 5 minutes for profiling and test runs
#SBATCH --job-name=testing

# Set OpenMP variables
export OMP_NUM_THREADS=8
export OMP_PLACES=cores
export OMP_PROC_BIND=close
export OMP_DISPLAY_AFFINITY=TRUE

# Load MPI module if needed
module load openMPI/5.0.5

# Executable base name
EXEC=./main

# Arguments to executable
ARGS="-x 10000 -y 10000 -n 50 -o 0"

echo "Running default, non-optimized version"
mpicc -o main -O3  -Iinclude stencil_template_parallel.c
mpirun --map-by none -np 1 ./main -x 256 -y 256 -n 100 -e 30 -p 1 > output.log
$EXEC $ARGS > default_run.log
